apply plugin: 'io.spring.convention.spring-module'

dependencies {
	management platform(project(":bjca-footstone-bpring-security-dependencies"))
	api project(':bjca-footstone-bpring-security-core')
	api project(':bjca-footstone-bpring-security-web')
	api 'cn.bjca.footstone.bpring:bjca-footstone-bpring-core'
	api 'cn.bjca.footstone.bpring:bjca-footstone-bpring-test'

	optional project(':bjca-footstone-bpring-security-config')
	optional project(':bjca-footstone-bpring-security-oauth2-client')
	optional project(':bjca-footstone-bpring-security-oauth2-jose')
	optional project(':bjca-footstone-bpring-security-oauth2-resource-server')
	optional 'io.projectreactor:reactor-core'
	optional 'cn.bjca.footstone.bpring:bjca-footstone-bpring-webmvc'
	optional 'cn.bjca.footstone.bpring:bjca-footstone-bpring-webflux'

	provided 'jakarta.servlet:jakarta.servlet-api'

	testImplementation project(path : ':bjca-footstone-bpring-security-config', configuration : 'tests')
	testImplementation 'com.fasterxml.jackson.core:jackson-databind'
	testImplementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'
	testImplementation 'io.projectreactor:reactor-test'
	testImplementation 'jakarta.xml.bind:jakarta.xml.bind-api'
	testImplementation "org.assertj:assertj-core"
	testImplementation "org.junit.jupiter:junit-jupiter-api"
	testImplementation "org.junit.jupiter:junit-jupiter-params"
	testImplementation "org.junit.jupiter:junit-jupiter-engine"
	testImplementation "org.mockito:mockito-core"
	testImplementation 'org.mockito:mockito-inline'
	testImplementation "org.mockito:mockito-junit-jupiter"
	testImplementation "cn.bjca.footstone.bpring:bjca-footstone-bpring-test"
	testImplementation 'org.skyscreamer:jsonassert'
	testImplementation 'cn.bjca.footstone.bpring:bjca-footstone-bpring-webmvc'
	testImplementation 'cn.bjca.footstone.bpring:bjca-footstone-bpring-tx'
}
