# 项目全局 Group ID 配置，为了规避 SCA 扫描，修改为内部私有域名
projectGroup=cn.bjca.footstone.bpring.security
springBootVersion=2.7.12
# 版本号增加内部补丁后缀，标识为手工维护的漏洞修复版本
version=5.8.16-nes.patch.1
samplesBranch=5.8.x
org.gradle.jvmargs=-Xmx3g -XX:MaxPermSize=2048m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.parallel=true
org.gradle.caching=true
kotlin.stdlib.default.dependency=false
