plugins {
	id 'java-test-fixtures'
}

apply plugin: 'io.spring.convention.spring-module'

dependencies {
	management platform(project(":bjca-footstone-bpring-security-dependencies"))
	optional 'cn.bjca.footstone.bpring:bjca-footstone-bpring-jcl'
	optional 'cn.bjca.footstone.bpring:bjca-footstone-bpring-core'
	optional 'org.bouncycastle:bcpkix-jdk18on'

	testFixturesImplementation "org.assertj:assertj-core"

	testImplementation "org.assertj:assertj-core"
	testImplementation "org.junit.jupiter:junit-jupiter-api"
	testImplementation "org.junit.jupiter:junit-jupiter-params"
	testImplementation "org.junit.jupiter:junit-jupiter-engine"
	testImplementation "org.mockito:mockito-core"
	testImplementation "org.mockito:mockito-junit-jupiter"
	testImplementation "cn.bjca.footstone.bpring:bjca-footstone-bpring-test"

	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
